/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as HomeRouteImport } from './routes/home'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/home': typeof HomeRoute
  '/ranking': typeof RankingRoute
  '/signin': typeof SigninRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding/role': typeof OnboardingRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/home': typeof HomeRoute
  '/ranking': typeof RankingRoute
  '/signin': typeof SigninRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding/role': typeof OnboardingRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/home': typeof HomeRoute
  '/ranking': typeof RankingRoute
  '/signin': typeof SigninRoute
  '/welcome': typeof WelcomeRoute
  '/onboarding/role': typeof OnboardingRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/home'
    | '/ranking'
    | '/signin'
    | '/welcome'
    | '/onboarding/role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/home'
    | '/ranking'
    | '/signin'
    | '/welcome'
    | '/onboarding/role'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/home'
    | '/ranking'
    | '/signin'
    | '/welcome'
    | '/onboarding/role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  HomeRoute: typeof HomeRoute
  RankingRoute: typeof RankingRoute
  SigninRoute: typeof SigninRoute
  WelcomeRoute: typeof WelcomeRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  HomeRoute: HomeRoute,
  RankingRoute: RankingRoute,
  SigninRoute: SigninRoute,
  WelcomeRoute: WelcomeRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
